### ISSUE TITLE
LICENSE file doesn't match license in README

### ISSUE THREAD

**Issue by skwashd** [govcms-training/site-builder#2]
The README says the project is licensed under the terms of the CC-BY-SA. The LICENSE files says it is CC-BY-NC-ND. Please update one of the files so they match. I would submit a PR, but I'm not sure which license you intend to use.

**Comment by nathan-w** [comment]
Agree @skwashd this doesn't match the intent of the materials being made available, and the inconsistent licence isn't right. Will discuss with Salsa Digital to determine the correct licence.

**Comment by kristydv** [comment]
Thanks for raising this @skwashd - the license has been updated in the LICENSE file, the README.md file and in the docx and PDF files. I'll close this ticket for now, but reopen if there any further comments.
