### ISSUE TITLE
Can't access User->Roles

### ISSUE THREAD

**Issue by nickausten-salsa** [govcms-training/site-builder#34]
Not available from menu so trainees will not be able to do Ex.1.1

<img width="938" alt="Screen Shot 2022-06-30 at 12 03 23 pm" src="https://user-images.githubusercontent.com/76456611/176576955-2bb70603-6146-4ae3-8fa1-b2912e6bfc9b.png">

**Comment by klonos** [comment]
This should now be fixed with https://projects.govcms.gov.au/GovCMS/govcms-training/-/commit/a66a824ae8d5ea3c801288d10b742ca96c342780

Can you please confirm and close this issue @nickausten-salsa? Thanks

**Comment by nickausten-salsa** [comment]
Looks good thanks
