### ISSUE TITLE
Can't access admin/config/people/accounts

### ISSUE THREAD

**Issue by nickausten-salsa** [govcms-training/site-builder#35]
Can't access Account Settings from /admin/config/people page.

Required for exercise 1.2

<img width="833" alt="Screen Shot 2022-06-30 at 12 05 58 pm" src="https://user-images.githubusercontent.com/76456611/176577295-65446e4e-0d10-4747-b1d1-e5c4cb57fe7d.png">

**Comment by klonos** [comment]
This should now be fixed with https://projects.govcms.gov.au/GovCMS/govcms-training/-/commit/4a5dc0be794bef270fa5e27ad2b832207990c82f

Can you please confirm and close this issue @nickausten-salsa? Thanks

**Comment by nickausten-salsa** [comment]
Yes able to access now thanks
