### ISSUE TITLE
Manual: Exercise is spelt incorrectly "Exercuse"

### ISSUE THREAD

**Issue by ryansnowden** [govcms-training/site-builder#47]
(menu and title)

https://salsa-digital.gitbook.io/govcms-site-builder/unit-2-designing-and-planning-content/designing-and-planning-content/exercise-2-1-compare-content-types-out-of-the-box  

<img width="1177" alt="Screenshot 2024-05-22 at 2 27 18 PM" src="https://github.com/govcms-training/content-admin/assets/328108/26c8b318-a6ac-4c1a-a831-728e1a553f5e">

**Comment by rebelmusic** [comment]
Thanks for catching this! It's fixed now.
